export default [
  {
    "id": "1",
    "store_brand": "京世沙龙",
    "store_name": "上海京世发型美容店",
    "store_license_name": "上海京世发型美容店川沙路店",
    "store_license_code": "91310115MA1H8RFH6R ",
    "store_license_address": "上海市浦东新区川沙路5398号3楼G61-F03-1-004 ",
    "store_license_date": "3/28/17",
    "store_license_operator": "庞守中",
    "store_license_scope": "美容店，美发店，保健按摩服务。",
    "store_facebook_level": "",
    "store_responsible_person": "朱利军",
    "store_consume_complain_number": "13816329884",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/1.png",
    "store_filings": []
  },
  {
    "id": "2",
    "store_brand": "tutuanna",
    "store_name": "主体变更营业执照办理中",
    "store_license_name": "上田商工（上海）服饰商贸有限公司 ",
    "store_license_code": "9131000066936464X7 ",
    "store_license_address": "上海市徐汇区天钥桥路30号1001-1005、1012室 ",
    "store_license_date": "12/19/07",
    "store_license_operator": "日野将彰",
    "store_license_scope": "纺织制品及原料、服装及配饰、鞋帽、日用百货、化妆品的进出口、批发、零售（限分支机构）、佣金代理（拍卖除外），其他相关配套业务。（不涉及国营贸易管理商品，涉及配额、许可证管理商品的，按国家有关规定办理申请）",
    "store_facebook_level": "",
    "store_responsible_person": "黄琳",
    "store_consume_complain_number": "68306788",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/2.png",
    "store_filings": []
  },
  {
    "id": "3",
    "store_brand": "屈臣氏",
    "store_name": "上海屈臣氏日用品有限公司",
    "store_license_name": "上海屈臣氏日用品有限公司浦东川沙路分店",
    "store_license_code": "91310000MA1FL3UF91",
    "store_license_address": "上海市浦东新区川沙路5398号百联川沙购物中心地下一层G61-B01-1-041 ",
    "store_license_date": " 2017-04-24 ",
    "store_license_operator": "范丽敏",
    "store_license_scope": "食品流通（含酒）；百货零售（含化妆品、通讯器材、通讯设备、电子产品）；中西药品（限许可证内容）、医疗器械、计划生育用品零售；设计、制作、代理、发布国内外各类广告业务，经营相关的配套业务。",
    "store_facebook_level": "",
    "store_responsible_person": "曹蓓琳",
    "store_consume_complain_number": "02096911122",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/3.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150249750",
        "store_filing_project": "预包装食品销售( 含冷藏冷冻食品 ),特殊食品销售(保健食品 ,婴幼儿配方乳粉 )",
        "store_filing_date": "5/26/22"
      },
      {
        "store_filing_code": "沪浦食药监械经营备20177092号",
        "store_filing_project": "零售:第二类医疗器械（仅限原不需许可的两批19个品种）",
        "store_filing_date": "/"
      }
    ]
  },
  {
    "id": "4",
    "store_brand": "一代眼镜",
    "store_name": "上海一代眼镜有限公司",
    "store_license_name": "上海一代眼镜有限公司川沙路分公司 ",
    "store_license_code": "91310115MA1H8R6Y8A ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-029",
    "store_license_date": "3/24/17",
    "store_license_operator": "马增杰",
    "store_license_scope": "眼镜的销售及修理，日用百货、办公用品、工艺品（除金银）的销售，验光配镜，医疗器械经营。",
    "store_facebook_level": "",
    "store_responsible_person": "马列波",
    "store_consume_complain_number": "50969015",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "按上海眼镜协会规定",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/4.png",
    "store_filings": [
      {
        "store_filing_code": "沪浦食药监械经营许20177014号",
        "store_filing_project": "三类：6822医用光学器具、仪器及内窥镜设备(限软性角膜接触镜及护理液)***",
        "store_filing_date": "7/5/22"
      }
    ]
  },
  {
    "id": "5",
    "store_brand": "柯泰儿",
    "store_name": "上海创一物贸有限公司",
    "store_license_name": "上海创一物贸有限公司浦东分公司",
    "store_license_code": "91310115MA1H8U6D4T  ",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B1-1-025室",
    "store_license_date": "4/13/17",
    "store_license_operator": "张倩",
    "store_license_scope": "化妆品的销售，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "李婷",
    "store_consume_complain_number": "13671993681",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/5.png",
    "store_filings": []
  },
  {
    "id": "6",
    "store_brand": "联华生活馆",
    "store_name": "上海联华超市发展有限公司",
    "store_license_name": "上海联华超市发展有限公司川沙路店",
    "store_license_code": "91310115MA1H8RM28J ",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B1-1-023室 ",
    "store_license_date": "3/29/17",
    "store_license_operator": "褚斌",
    "store_license_scope": "日用百货、五金交电、工艺品、装潢材料、体育用品、健身器材、食用农产品、化妆品、卫生洁具、箱包、厨房用品、针纺织品、电子产品、服装鞋帽、文教用品、花卉、通信设备的销售，医疗器械经营，烟草专卖零售，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "张敏",
    "store_consume_complain_number": "50655262",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/6.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150245321",
        "store_filing_project": "预包装食品销售( 含冷藏冷冻食品 ),散装食品销售(含冷藏冷冻食品 ,不含熟食 ),特殊食品销售(保健食品 ,婴幼儿配方乳粉 ),其他类食品销售(含生猪产品 ,含牛羊肉 ),热食类食品制售(简单加热 )",
        "store_filing_date": "5/21/22"
      },
      {
        "store_filing_code": "沪浦食药监械经营备20177060号",
        "store_filing_project": "零售:第二类医疗器械（仅限原不需许可的两批19个品种）",
        "store_filing_date": "/"
      }
    ]
  },
  {
    "id": "7",
    "store_brand": "惟丽尚品",
    "store_name": "南通快尚家居用品有限公司有限公司",
    "store_license_name": "南通快尚家居用品有限公司有限公司上海川沙分公司",
    "store_license_code": "91310115MA1H8W072K",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-026室 ",
    "store_license_date": "4/24/17",
    "store_license_operator": "蔡佳欢",
    "store_license_scope": "家居用品、日用百货、针纺织品及原料、服装服饰、鞋帽、化妆品、办公用品、体育用品、家用电器、电子产品的销售，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "蔡佳欢",
    "store_consume_complain_number": "18951330798",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/7.png",
    "store_filings": []
  },
  {
    "id": "8",
    "store_brand": "优禾生活",
    "store_name": "优禾生活实业（上海）有限公司",
    "store_license_name": "优禾生活实业（上海）有限公司浦东川沙百联分公司",
    "store_license_code": "91310115MA1H8Q7B3M",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B1-1-028",
    "store_license_date": "3/16/17",
    "store_license_operator": "朱建祥",
    "store_license_scope": "食用农产品、化妆品、日用百货的销售，从事货物及技术的进出口业务，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "彭维翔",
    "store_consume_complain_number": "50969880",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/8.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150236715",
        "store_filing_project": "预包装食品销售(不含冷藏冷冻食品),散装食品销售(不含冷藏冷冻食品,不含熟食),特殊食品销售(保健食品销售)",
        "store_filing_date": "5/4/22"
      }
    ]
  },
  {
    "id": "9",
    "store_brand": "思乐得",
    "store_name": "上海思乐得家居用品有限公司",
    "store_license_name": "上海思乐得家居用品有限公司川沙店",
    "store_license_code": "913101153121979572 ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B1-1-024",
    "store_license_date": "4/18/17",
    "store_license_operator": "张斌",
    "store_license_scope": "不锈钢制品、酒店用品、金属材料，塑料制品、陶瓷制品、厨房设备、玻璃器皿、日用百货、办公用品、工艺品、通讯产品、计算机软硬件及辅助设备（除计算机信息系统安全专用产品）、电子元器件、五金交电、电器设备、装饰材料、汽车零配件、电子产品的销售，商务信息咨询、投资咨询（以上咨询均除经纪），旅游信息咨询（不得从事旅行社业务），会议与展览服务，计算机软硬件开发；花卉苗木种植；园林绿化工程；计算机专业领域内的技术咨询、技术开发、技术转让、技术服务，从事货物及技术的进出口业务。",
    "store_facebook_level": "",
    "store_responsible_person": "张利云",
    "store_consume_complain_number": "58908848",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/9.png",
    "store_filings": []
  },
  {
    "id": "10",
    "store_brand": "酷乐潮玩",
    "store_name": "宁波乐品汇商贸发展有限公司",
    "store_license_name": "宁波乐品汇商贸发展有限公司上海川沙百联店",
    "store_license_code": "91310115MA1H8T47XF",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B1-1-021商铺",
    "store_license_date": "4/1/17",
    "store_license_operator": "程敏贤 ",
    "store_license_scope": " 日用百货、文体用品、文具、纸制品",
    "store_facebook_level": "",
    "store_responsible_person": "刘敏",
    "store_consume_complain_number": "68302188",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/10.png",
    "store_filings": []
  },
  {
    "id": "11",
    "store_brand": "G-phone",
    "store_name": "上海激奋品牌管理股份有限公司",
    "store_license_name": "上海激奋品牌管理股份有限公司川沙百联店",
    "store_license_code": "91310000324268839L",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B1-1-020商铺",
    "store_license_date": "4/18/17",
    "store_license_operator": "倪佳新",
    "store_license_scope": "企业管理，通信专业技术领域内的技术开发、技术转让、技术咨询、技术服务，知识产权代理（除专利代理），市场营销策划，广告设计、制作，会展服务，企业形象策划，网络工程，通信建设工程施工，建筑智能化建设工程专业施工，企业管理咨询，市场信息咨询与调查(不得从事社会调查、社会调研、民意调查、民意测验)，计算机软件开发，电子数码产品、家电维修及销售，通信设备及配件、智能电子产品的开发、销售，建材、包装材料销售，仓储（除危险品），商务信息咨询（除经纪）。",
    "store_facebook_level": "",
    "store_responsible_person": "唐明",
    "store_consume_complain_number": "17717315181",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/11.png",
    "store_filings": []
  },
  {
    "id": "12",
    "store_brand": "三枪",
    "store_name": "上海三枪（集团）有限公司",
    "store_license_name": "上海三枪（集团）有限公司川沙店",
    "store_license_code": "91310000132217527D",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-017室 ",
    "store_license_date": "4/19/17",
    "store_license_operator": "范高智",
    "store_license_scope": "对外贸易经济合作部批准的进出口业务（按批文），国内贸易（除专项规定外）",
    "store_facebook_level": "",
    "store_responsible_person": "陆振娟",
    "store_consume_complain_number": "13761191727",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/12.png",
    "store_filings": []
  },
  {
    "id": "13",
    "store_brand": "热风",
    "store_name": "上海热风时尚企业发展有限公司",
    "store_license_name": "上海热风时尚企业发展有限公司川沙分公司",
    "store_license_code": "913101145726632805 ",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-044-047 ",
    "store_license_date": "4/27/17",
    "store_license_operator": "龚钊",
    "store_license_scope": "服装鞋帽、针纺织品、化妆品、皮革制品、日用百货、工艺品、珠宝首饰、电子设备、数码产品、五金交电、家用电器、通讯设备及相关产品、办公用品、文化用品、体育用品、劳防用品的销售，会务服务，企业管理咨询，室内外装潢工程，从事货物及技术的进出口业务。",
    "store_facebook_level": "",
    "store_responsible_person": "韦春飞",
    "store_consume_complain_number": "4008203310",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/13.png",
    "store_filings": []
  },
  {
    "id": "14",
    "store_brand": "宝乐迪",
    "store_name": "上海威红文化发展有限公司",
    "store_license_name": "上海威红文化发展有限公司",
    "store_license_code": "91310115MA1H83BC4Q ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-007室",
    "store_license_date": "8/11/16",
    "store_license_operator": "王良仓",
    "store_license_scope": "文化艺术交流活动策划，公关活动策划，企业形象策划，商务信息咨询，会展服务，烟草专卖零售，食品流通，娱乐场所（歌舞娱乐场所）。",
    "store_facebook_level": "",
    "store_responsible_person": "刘刚",
    "store_consume_complain_number": "50969655",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/14.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150243863",
        "store_filing_project": "预包装食品销售( 含冷藏冷冻食品 )",
        "store_filing_date": "5/17/22"
      }
    ]
  },
  {
    "id": "15",
    "store_brand": "影城",
    "store_name": "上海上影百联影院管理有限公司",
    "store_license_name": "上海上影百联影院管理有限公司川沙分公司",
    "store_license_code": "91310115MA1H8WA5XX",
    "store_license_address": "上海市浦东新区川沙路5398号第4F层G61-F04-1-006室",
    "store_license_date": "4/26/17",
    "store_license_operator": "周炯亮",
    "store_license_scope": "影院管理，电影放映，物业管理，从事影视技术领域内的技术开发、技术咨询、技术转让、技术服务，影视器材、音响设备、舞台设备及灯光系统设备的销售、安装，自有设备租赁，企业管理咨询，商务咨询，企业形象策划，市场营销策划，展览展示服务，礼仪服务，计算机软件设计、销售，日用百货、服装、工艺美术品（象牙及其制品除外）的销售，餐饮服务（饮品店），食品流通，各类广告的设计、制作、代理、发布。",
    "store_facebook_level": "",
    "store_responsible_person": "管华",
    "store_consume_complain_number": "50969811",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/15.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150259297",
        "store_filing_project": "预包装食品销售(含冷藏冷冻食品)、散装食品销售(含冷藏冷冻食品，不含熟食)；现制现售：热食类食品制售(简单加热，熟制坚果、籽类、豆类 (爆米花))、自制饮品制售(果蔬汁类)",
        "store_filing_date": "9/6/22"
      }
    ]
  },
  {
    "id": "16",
    "store_brand": "麦琪天地",
    "store_name": "璀其文化传播（上海）有限公司",
    "store_license_name": "璀其文化传播（上海）有限公司",
    "store_license_code": "91310115MA1H8W670F ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-016 ",
    "store_license_date": "4/25/17",
    "store_license_operator": "颜遥",
    "store_license_scope": "文化艺术交流活动策划，各类广告的设计、制作、代理、发布，室内儿童游乐场，摄影服务，会务服务，展览展示服务，市场营销策划，企业形象策划，商务咨询，礼仪服务，图文设计制作，电子商务（不得从事金融业务），餐饮企业管理，物业管理，服装鞋帽、玩具、工艺美术品（象牙及其制品除外）、装饰品、办公用品、日用百货、金属制品、建筑装潢材料、电子产品、计算机、软件及辅助设备、通讯设备的销售，从事货物及技术的进出口业务。",
    "store_facebook_level": "",
    "store_responsible_person": "俞淑娥",
    "store_consume_complain_number": "50878865",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/16.png",
    "store_filings": []
  },
  {
    "id": "17",
    "store_brand": "奇思梦工坊",
    "store_name": "上海爱佳佳教育培训有限公司",
    "store_license_name": "上海爱佳佳教育培训有限公司",
    "store_license_code": "9131011508794103XY ",
    "store_license_address": "上海市浦东新区城西路227、229、231、233、239号 ",
    "store_license_date": "2/14/14",
    "store_license_operator": "黄福祥",
    "store_license_scope": "教育培训（快乐数学、易学英语、汉语文学、趣味物理）。",
    "store_facebook_level": "",
    "store_responsible_person": "王璟元",
    "store_consume_complain_number": "58900621",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/17.png",
    "store_filings": []
  },
  {
    "id": "18",
    "store_brand": "积家",
    "store_name": "稷伽（上海）实业有限公司",
    "store_license_name": "稷伽（上海）实业有限公司浦东分公司 ",
    "store_license_code": "91310115MA1H8UL97F ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-020室",
    "store_license_date": "4/19/17",
    "store_license_operator": "阎萍",
    "store_license_scope": "玩具、日用百货、化妆品、服装鞋帽、电子产品、纸制品、宠物用品、建材、金属制品、塑料制品、普通劳防用品、办公用品、五金交电、工艺美术品（象牙及其制品除外）、机电设备的销售，电子商务（不得从事金融业务），从事货物及技术的进出口业务，企业形象策划，市场营销策划，婚庆礼仪服务，展览展示服务，各类广告的设计、制作，电脑图文设计制作，商务咨询，企业管理咨询，会务会展服务，园林绿化工程。",
    "store_facebook_level": "",
    "store_responsible_person": "鞠莉",
    "store_consume_complain_number": "58960388",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/18.png",
    "store_filings": []
  },
  {
    "id": "19",
    "store_brand": "炫动酷地带",
    "store_name": "上海开心娃娃数码影像制作有限公司",
    "store_license_name": "上海开心娃娃数码影像制作有限公司第三分公司 ",
    "store_license_code": "91310115MA1H8TRH80 ",
    "store_license_address": "上海市浦东新区川沙路5398号3F层G61-3F-1-017 ",
    "store_license_date": "4/10/17",
    "store_license_operator": "孙爱军",
    "store_license_scope": "摄影、摄像，个人形象设计，工艺美术品、摄影器材、百货的销售，婚纱礼服出租。",
    "store_facebook_level": "",
    "store_responsible_person": "王艳",
    "store_consume_complain_number": "58960561",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/19.png",
    "store_filings": []
  },
  {
    "id": "20",
    "store_brand": "能力风暴",
    "store_name": "上海开心娃娃数码影像制作有限公司",
    "store_license_name": "上海开心娃娃数码影像制作有限公司第四分公司 ",
    "store_license_code": "91310115MA1H8TRB9W ",
    "store_license_address": "上海市浦东新区川沙路5398号第3F层G61-3F-1-011B室 ",
    "store_license_date": "4/10/17",
    "store_license_operator": "孙爱军",
    "store_license_scope": "摄影摄像服务，形象设计，工艺美术品（象牙及其制品除外）、摄影器材、百货的销售，婚庆礼仪服务。",
    "store_facebook_level": "",
    "store_responsible_person": "",
    "store_consume_complain_number": "",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/20.png",
    "store_filings": []
  },
  {
    "id": "21",
    "store_brand": "ABS",
    "store_name": "爱彼此电子商务（上海）有限公司",
    "store_license_name": "爱彼此电子商务（上海）有限公司川沙二店 ",
    "store_license_code": "91310115MA1H8R8J89",
    "store_license_address": "上海市浦东新区川沙路5398号第2F层G61-2F-1-006室 ",
    "store_license_date": "3/27/17",
    "store_license_operator": "刘诚非",
    "store_license_scope": "家居用品、日用百货、针纺织品及原料、服装服饰、鞋帽、化妆品、办公用品、体育用品、家用电器、电子产品的销售，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "曹主金",
    "store_consume_complain_number": "4008205077",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/21.png",
    "store_filings": [
      {
        "store_filing_code": "流通证办的是绿地里的分公司",
        "store_filing_project": "",
        "store_filing_date": ""
      }
    ]
  },
  {
    "id": "22",
    "store_brand": "茂昌",
    "store_name": "上海三联(集团)有限公司",
    "store_license_name": "上海三联（集团）有限公司茂昌眼镜川沙路店",
    "store_license_code": "91310115MA1H8UGB18",
    "store_license_address": "上海市浦东新区川沙路5398号第1F层G61-F01-1-010C",
    "store_license_date": "4/18/17",
    "store_license_operator": "柳昊雁",
    "store_license_scope": "验光配镜，眼镜修理，家用电器、工艺美术品（象牙及其制品除外）的销售，食品流通，医疗器械经营。",
    "store_facebook_level": "",
    "store_responsible_person": "唐先生",
    "store_consume_complain_number": "58645821",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "上海眼镜商业协会规定",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/22.png",
    "store_filings": [
      {
        "store_filing_code": "沪浦食药监械经营许20177015号",
        "store_filing_project": "三类：6822医用光学器具、仪器及内窥镜设备(限软性角膜接触镜及护理液)***",
        "store_filing_date": "7/12/22"
      }
    ]
  },
  {
    "id": "23",
    "store_brand": "MUJI",
    "store_name": "联营联销用百联执照",
    "store_license_name": "无印良品（上海）商业有限公司",
    "store_license_code": "913100007747635381 ",
    "store_license_address": "上海市静安区南京西路1601号35楼3501-3508室 ",
    "store_license_date": "5/18/05",
    "store_license_operator": "铃木啓（SUZUKI KEI）",
    "store_license_scope": "服装、服饰、鞋帽、饰品及珠宝饰品、毛毡类饰品、日常生活用品、化妆品、玩具、文具、家具、家用电器、文化用品、自行车及零部件、花卉苗木、食品流通、图书报刊、酒类商品的零售（限分支机构经营）和批发，餐饮（限分支机构经营），商务信息咨询，企业营销策划（广告除外），自营商品进口，采购国内产品出口，及其他相关配套业务。（不涉及国营贸易管理商品，涉及配额、许可证管理商品的按照国家有关规定办理申请）。",
    "store_facebook_level": "",
    "store_responsible_person": "佳作权",
    "store_consume_complain_number": "58267881",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/23.png",
    "store_filings": []
  },
  {
    "id": "24",
    "store_brand": "LOHO",
    "store_name": "上海驭将商贸有限公司",
    "store_license_name": "上海驭将商贸有限公司川沙店",
    "store_license_code": "91310115MA1H8RWJ02 ",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B1-1-034室 ",
    "store_license_date": "3/31/17",
    "store_license_operator": "孙超",
    "store_license_scope": "从事货物及技术的进出口业务，眼镜及配件、光学仪器及配件、五金交电、日用百货、电子产品、金银饰品、金属材料及制品、纺织原料及产品、橡塑制品、玻璃制品、工艺品、化妆品、服装鞋帽、机械设备及配件、环保设备、仪器仪表的销售，商务信息咨询。",
    "store_facebook_level": "",
    "store_responsible_person": "张叶勤",
    "store_consume_complain_number": "4008871920",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/24.png",
    "store_filings": []
  },
  {
    "id": "25",
    "store_brand": "卡西欧",
    "store_name": "上海时川商贸有限公司",
    "store_license_name": "上海时川商贸有限公司",
    "store_license_code": "91310115MA1H8U7043 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-030 ",
    "store_license_date": "4/13/17",
    "store_license_operator": "王主晶",
    "store_license_scope": "日用百货、五金交电、办公设备、工艺礼品、针织品、服装服饰、钟表的销售，钟表维修，商务信息咨询。",
    "store_facebook_level": "",
    "store_responsible_person": "王主晶",
    "store_consume_complain_number": "15921965635",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/25.png",
    "store_filings": []
  },
  {
    "id": "26",
    "store_brand": "咪哒K",
    "store_name": "上海浦东普宝工贸有限公司",
    "store_license_name": "上海浦东普宝工贸有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8UTF7P ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-011B",
    "store_license_date": "4/20/17",
    "store_license_operator": "杨青青",
    "store_license_scope": "金属材料、五金交电、机电设备、化工原料及产品（除危险化学品、监控化学品、民用爆炸物品、易制毒化学品）、汽车配件、日用百货的销售。",
    "store_facebook_level": "",
    "store_responsible_person": "吴顺",
    "store_consume_complain_number": "13564615973",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/26.png",
    "store_filings": []
  },
  {
    "id": "27",
    "store_brand": "优衣库",
    "store_name": "优衣库商贸有限公司",
    "store_license_name": "优衣库商贸有限公司上海浦东川沙路店 ",
    "store_license_code": "91310000MA1FY6NY97 ",
    "store_license_address": "上海市浦东新区川沙路5398号地下一层G61-B01-027号",
    "store_license_date": "4/28/17",
    "store_license_operator": "西村昌巳",
    "store_license_scope": "服装及其配件、装饰品、鞋、伞、箱包、眼镜（除隐形眼镜及护理液）、毛巾、床上用品、洗浴用品、化妆用品、运动器材的零售、批发。",
    "store_facebook_level": "",
    "store_responsible_person": "杨军",
    "store_consume_complain_number": "50969102",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/27.png",
    "store_filings": []
  },
  {
    "id": "28",
    "store_brand": "好蛋仔",
    "store_name": "上海好蛋仔餐饮管理有限公司",
    "store_license_name": "上海好蛋仔餐饮管理有限公司川沙百联店 ",
    "store_license_code": "91310115MA1H8R6BXP ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-001B室",
    "store_license_date": "3/24/17",
    "store_license_operator": "郝庆芸",
    "store_license_scope": "餐饮服务（现制现售饮料、焙烤食品）。",
    "store_facebook_level": "",
    "store_responsible_person": "蔺亚龙",
    "store_consume_complain_number": "17302120566",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "17302120566",
    "store_qrcode": "img/qrcodes/28.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230363",
        "store_filing_project": "糕点类食品制售(中式干点),自制饮品制售(茶,风味饮料)",
        "store_filing_date": "4/24/22"
      }
    ]
  },
  {
    "id": "29",
    "store_brand": "三花奶奶",
    "store_name": "珊花（上海）餐饮管理有限公司",
    "store_license_name": "珊花（上海）餐饮管理有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8R597U ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-002A室 ",
    "store_license_date": "3/24/17",
    "store_license_operator": "顾洁伟",
    "store_license_scope": "餐饮服务（饮品店）。",
    "store_facebook_level": "",
    "store_responsible_person": "常忠纪",
    "store_consume_complain_number": "50969117",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50969117",
    "store_qrcode": "img/qrcodes/29.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150229767",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "30",
    "store_brand": "快乐柠檬",
    "store_name": "上海晶赢餐饮管理有限公司",
    "store_license_name": "上海晶赢餐饮管理有限公司第二分公司 ",
    "store_license_code": "91310115MA1H8Q7X38",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-002B ",
    "store_license_date": "3/16/17",
    "store_license_operator": "陆如茵 ",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "陆如茵",
    "store_consume_complain_number": "13916688112",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品1小时",
    "store_take_out_number": "50968577",
    "store_qrcode": "img/qrcodes/30.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230209",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "31",
    "store_brand": "果之满满",
    "store_name": "上海生一投资管理有限公司",
    "store_license_name": "上海生一投资管理有限公司璞茹饮品店 ",
    "store_license_code": "91310115MA1H8RQA9Y ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-035B室 ",
    "store_license_date": "3/30/17",
    "store_license_operator": "高小琴",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "王小权",
    "store_consume_complain_number": "50652195",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品1小时",
    "store_take_out_number": "50652195",
    "store_qrcode": "img/qrcodes/31.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150225223",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/13/22"
      }
    ]
  },
  {
    "id": "32",
    "store_brand": "莉莲",
    "store_name": "上海茱莉亚食品有限公司",
    "store_license_name": "上海茱莉亚食品有限公司翔川路店",
    "store_license_code": "91310115MA1H8RGB30",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-003室 ",
    "store_license_date": "3/28/17",
    "store_license_operator": "毛美丽",
    "store_license_scope": "餐饮服务（焙烤食品）。",
    "store_facebook_level": "",
    "store_responsible_person": "李健",
    "store_consume_complain_number": "50969695",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "见包装",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/32.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150227547",
        "store_filing_project": "糕点类食品制售(含冷加工糕点),预包装食品销售(含冷藏冷冻食品),散装食品销售(含冷藏冷冻食品,不含熟食)[仅限环保部门限定的不产生油烟的餐饮项目]",
        "store_filing_date": "4/18/22"
      }
    ]
  },
  {
    "id": "33",
    "store_brand": "友丽拌饭",
    "store_name": "上海友丽餐饮有限公司",
    "store_license_name": "上海友丽餐饮有限公司川沙百联店",
    "store_license_code": "91310115MA1H8TRM97 ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-004室",
    "store_license_date": "4/10/17",
    "store_license_operator": "陆贇",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "童莎莎",
    "store_consume_complain_number": "50969717",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50969717",
    "store_qrcode": "img/qrcodes/33.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230049",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "34",
    "store_brand": "和缘",
    "store_name": "上海妙侬餐饮管理有限公司",
    "store_license_name": "上海妙侬餐饮管理有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8T9Y20 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-005室 ",
    "store_license_date": "4/5/17",
    "store_license_operator": "谢弋 ",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "管智胤",
    "store_consume_complain_number": "50969377",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50969377",
    "store_qrcode": "img/qrcodes/34.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245243",
        "store_filing_project": "热食类食品制售,生食类食品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "35",
    "store_brand": "詹姆士",
    "store_name": "上海王女己家餐饮管理有限公司",
    "store_license_name": "上海王女己家餐饮管理有限公司川沙路分公司 ",
    "store_license_code": "91310115MA1H8QPU31 ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B1-1-006 ",
    "store_license_date": "3/21/17",
    "store_license_operator": "沈佳佳",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "缪玲",
    "store_consume_complain_number": "50171817",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50171817",
    "store_qrcode": "img/qrcodes/35.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245315",
        "store_filing_project": "热食类食品制售,自制饮品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "36",
    "store_brand": "小杨生煎",
    "store_name": "小杨生煎企业管理发展（上海）有限公司",
    "store_license_name": "小杨生煎企业管理发展（上海）有限公司浦东第七分公司 ",
    "store_license_code": "91310000MA1G0E1P27 ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-007号铺位 ",
    "store_license_date": "3/30/17",
    "store_license_operator": "杨利朋",
    "store_license_scope": "餐饮服务 。",
    "store_facebook_level": "",
    "store_responsible_person": "辛藤藤",
    "store_consume_complain_number": "50960577",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50960577",
    "store_qrcode": "img/qrcodes/36.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230073",
        "store_filing_project": "热食类食品制售,糕点类食品制售(中式干点)",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "37",
    "store_brand": "家有好面",
    "store_name": "上海家有好面餐饮管理有限公司",
    "store_license_name": "上海家有好面餐饮管理有限公司川沙路店 ",
    "store_license_code": "91310000MA1JLWT29A ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-008商铺 ",
    "store_license_date": "5/10/17",
    "store_license_operator": "董元",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "张志民",
    "store_consume_complain_number": "50969277",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/37.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150254639",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "6/5/22"
      }
    ]
  },
  {
    "id": "38",
    "store_brand": "谷田稻香",
    "store_name": "上海新田餐饮有限公司",
    "store_license_name": "上海新田餐饮有限公司川沙路分公司 ",
    "store_license_code": "91310115MA1H8Q877K ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-011 ",
    "store_license_date": " 2017-03-16 ",
    "store_license_operator": "戴磊",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "段冬香",
    "store_consume_complain_number": "50969200",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/38.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150227563",
        "store_filing_project": "热食类食品制售,自制饮品制售",
        "store_filing_date": "4/18/22"
      }
    ]
  },
  {
    "id": "39",
    "store_brand": "精悦蓉",
    "store_name": "精悦蓉餐饮管理（上海）有限公司",
    "store_license_name": "精悦蓉餐饮管理（上海）有限公司川沙路分公司 ",
    "store_license_code": "91310115MA1H8RD12H ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-049B室 ",
    "store_license_date": "3/27/17",
    "store_license_operator": "陈海颺",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "霍星星",
    "store_consume_complain_number": "50307530",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/39.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150227555",
        "store_filing_project": "热食类食品制售,冷食类食品制售",
        "store_filing_date": "4/18/22"
      }
    ]
  },
  {
    "id": "40",
    "store_brand": "阿香米线",
    "store_name": "上海维德是尊餐饮有限公司",
    "store_license_name": "上海维德是尊餐饮有限公司",
    "store_license_code": "91310115MA1H8QR27Y ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-010 ",
    "store_license_date": "3/22/17",
    "store_license_operator": "何勇",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "靳培培",
    "store_consume_complain_number": "17721116727",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/40.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232529",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "41",
    "store_brand": "拿渡",
    "store_name": "上海佰彦餐饮有限公司",
    "store_license_name": "上海佰彦餐饮有限公司川沙分公司",
    "store_license_code": "91310115MA1H8RMK5T ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-009 ",
    "store_license_date": "3/29/17",
    "store_license_operator": "朱涛",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "洪玉",
    "store_consume_complain_number": "50960990",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/41.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232537",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "42",
    "store_brand": "一点点",
    "store_name": "上海市浦东新区川沙新镇望梅饮品店",
    "store_license_name": "上海市浦东新区川沙新镇望梅饮品店",
    "store_license_code": "310115601795272",
    "store_license_address": "浦东新区川沙新镇川沙路5398号G61-B01-1-050B室 ",
    "store_license_date": "4/12/17",
    "store_license_operator": "郑丐水",
    "store_license_scope": "餐饮服务(现制现售饮料、冷冻饮品及果蔬）。",
    "store_facebook_level": "",
    "store_responsible_person": "郑孟",
    "store_consume_complain_number": "17701868311",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "17701868311",
    "store_qrcode": "img/qrcodes/42.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150243547",
        "store_filing_project": "自制饮品制售(果蔬汁,果蔬汁饮料,风味饮料,茶,咖啡,植物饮料)[仅限环保部门限定的不产生油烟的餐饮项目]",
        "store_filing_date": "2/19/20"
      }
    ]
  },
  {
    "id": "43",
    "store_brand": "加牛站",
    "store_name": "上海文砚餐饮管理有限公司",
    "store_license_name": "上海文砚餐饮管理有限公司第一分公司 ",
    "store_license_code": "91310115MA1H8QT2XQ ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-051铺位 ",
    "store_license_date": "3/22/17",
    "store_license_operator": "周俊",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "靳婷婷",
    "store_consume_complain_number": "50969355",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "50969355",
    "store_qrcode": "img/qrcodes/43.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245250",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "44",
    "store_brand": "继光香香鸡",
    "store_name": "上海闻圣餐饮管理有限公司",
    "store_license_name": "上海闻圣餐饮管理有限公司第二分公司 ",
    "store_license_code": "91310115MA1H8Q7F63 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-052A室 ",
    "store_license_date": "3/16/17",
    "store_license_operator": "王圣园",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "李翠梅",
    "store_consume_complain_number": "17701695400",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "17701695400",
    "store_qrcode": "img/qrcodes/44.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245189",
        "store_filing_project": "热食类食品制售(炸,烤肉类 )",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "45",
    "store_brand": "红唇",
    "store_name": "上海红唇餐饮管理有限公司",
    "store_license_name": "上海红唇餐饮管理有限公司川沙路店 ",
    "store_license_code": "91310115MA1H8QU267 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B1-1-052B ",
    "store_license_date": "3/22/17",
    "store_license_operator": "张然",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "余承树",
    "store_consume_complain_number": "17612188346",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品12小时",
    "store_take_out_number": "15026586439",
    "store_qrcode": "img/qrcodes/45.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245163",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "46",
    "store_brand": "特别牛",
    "store_name": "晓然（上海）餐饮有限公司",
    "store_license_name": "晓然（上海）餐饮有限公司",
    "store_license_code": "91310115MA1H8RTD2P ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-053室 ",
    "store_license_date": "3/30/17",
    "store_license_operator": "梁然",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "张真真",
    "store_consume_complain_number": "15821515320",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品20分钟",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/46.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245147",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "47",
    "store_brand": "大鼓米线",
    "store_name": "上海大鼓餐饮管理有限公司",
    "store_license_name": "上海大鼓餐饮管理有限公司川沙店",
    "store_license_code": "91310115MA1H8R52XQ ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-013室 ",
    "store_license_date": "3/24/17",
    "store_license_operator": "朱培荣",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "罗先生",
    "store_consume_complain_number": "13032160615",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品1小时",
    "store_take_out_number": "13032160615",
    "store_qrcode": "img/qrcodes/47.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245155",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "48",
    "store_brand": "一捏私厨",
    "store_name": "上海一捏餐饮管理有限公司",
    "store_license_name": "上海一捏餐饮管理有限公司川沙店",
    "store_license_code": "91310115MA1H8TNB39 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-014/015室",
    "store_license_date": "4/7/17",
    "store_license_operator": "王森",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "龚玉霞",
    "store_consume_complain_number": "50969916",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品3小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/48.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230057",
        "store_filing_project": "热食类食品制售,冷食类食品制售, 糕点类食品制售(中式干点 ),自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "49",
    "store_brand": "锋厨",
    "store_name": "上海梓强餐饮管理有限公司",
    "store_license_name": "上海梓强餐饮管理有限公司川沙百联一店",
    "store_license_code": "91310115MA1H8R5036",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-049A1室",
    "store_license_date": "3/24/17",
    "store_license_operator": "王海峰",
    "store_license_scope": "餐饮服务（饮品店）。",
    "store_facebook_level": "",
    "store_responsible_person": "王之翠",
    "store_consume_complain_number": "15800380228",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/49.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230233",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/24/22"
      }
    ]
  },
  {
    "id": "50",
    "store_brand": "馍道",
    "store_name": "上海梓强餐饮管理有限公司",
    "store_license_name": "上海梓强餐饮管理有限公司川沙百联二店",
    "store_license_code": "91310115MA1H8R5629",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-049A2室",
    "store_license_date": "3/24/17",
    "store_license_operator": "王海峰",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "岩英",
    "store_consume_complain_number": "15800380228",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品2小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/50.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150244013",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/17/22"
      }
    ]
  },
  {
    "id": "51",
    "store_brand": "掌上韩品",
    "store_name": "上海亿州餐饮有限公司",
    "store_license_name": "上海亿州餐饮有限公司",
    "store_license_code": "91310115MA1H8TH72M ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-043室",
    "store_license_date": "4/6/17",
    "store_license_operator": "王雪芬",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "王俊",
    "store_consume_complain_number": "17665347722",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品2小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/51.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230103",
        "store_filing_project": "热食类食品制售,自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "52",
    "store_brand": "天御皇茶",
    "store_name": "上海市浦东新区川沙新镇尚承饮品店",
    "store_license_name": "上海市浦东新区川沙新镇尚承饮品店",
    "store_license_code": "310115601804412",
    "store_license_address": "浦东新区川沙新镇川沙路5398号G61-B01-1-037B室 ",
    "store_license_date": "5/8/17",
    "store_license_operator": "陈颖",
    "store_license_scope": "餐饮服务（饮品店）。",
    "store_facebook_level": "",
    "store_responsible_person": "张琼",
    "store_consume_complain_number": "52999185",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时",
    "store_take_out_number": "52999185",
    "store_qrcode": "img/qrcodes/52.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150238261",
        "store_filing_project": "自制饮品制售[仅限环保部门限定的不产生油烟的餐饮项目]",
        "store_filing_date": "4/26/20"
      }
    ]
  },
  {
    "id": "53",
    "store_brand": "爱茜茜里",
    "store_name": "上海仟果企业管理有限公司",
    "store_license_name": "上海仟果企业管理有限公司川沙路分公司 ",
    "store_license_code": "91310115MA1H8RK68B ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-037A室 ",
    "store_license_date": " 2017/3/29 ",
    "store_license_operator": "范虹",
    "store_license_scope": "餐饮服务（饮品店）。",
    "store_facebook_level": "",
    "store_responsible_person": "郭彪",
    "store_consume_complain_number": "50563811",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品半小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/53.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150224615",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/12/22"
      }
    ]
  },
  {
    "id": "54",
    "store_brand": "丸龟制面",
    "store_name": "上海佳面餐饮管理有限公司",
    "store_license_name": "上海佳面餐饮管理有限公司川沙路分公司",
    "store_license_code": "91310115MA1H8X6T3K ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B01-1-038 ",
    "store_license_date": "5/4/17",
    "store_license_operator": "盛维勇",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "杨鸣",
    "store_consume_complain_number": "50960992",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品2小时",
    "store_take_out_number": "50960992",
    "store_qrcode": "img/qrcodes/54.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150263043",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "6/19/22"
      }
    ]
  },
  {
    "id": "55",
    "store_brand": "争鲜",
    "store_name": "争鲜(上海)食品有限公司",
    "store_license_name": "争鲜（上海）食品有限公司浦东第十二分公司 ",
    "store_license_code": "91310000MA1J23J227 ",
    "store_license_address": "上海市浦东新区川沙路5398号B1层G61-B01-1-039室 ",
    "store_license_date": " 2017/4/17 ",
    "store_license_operator": "梁铭聪",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "谢炯",
    "store_consume_complain_number": "50969366",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品24小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/55.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230435",
        "store_filing_project": "热食类食品制售,生食类食品制售",
        "store_filing_date": "4/24/22"
      }
    ]
  },
  {
    "id": "56",
    "store_brand": "丸来玩趣",
    "store_name": "丸来玩趣（上海）投资发展有限公司",
    "store_license_name": "丸来玩趣（上海）投资发展有限公司玩趣餐饮店",
    "store_license_code": "91310115MA1H8WCA3X",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-050A室",
    "store_license_date": "4/26/17",
    "store_license_operator": " 李应",
    "store_license_scope": "餐饮服务",
    "store_facebook_level": "",
    "store_responsible_person": "张萍",
    "store_consume_complain_number": "13009179933",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品1小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/56.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150250491",
        "store_filing_project": "热食类食品制售",
        "store_filing_date": "5/27/22"
      }
    ]
  },
  {
    "id": "57",
    "store_brand": "泰煌鸡",
    "store_name": "上海泰煌餐饮管理有限公司",
    "store_license_name": "上海泰煌餐饮管理有限公司川沙店",
    "store_license_code": "91310115MA1H8RQU2T ",
    "store_license_address": "上海市浦东新区川沙路5398号第B1层G61-B01-1-048 ",
    "store_license_date": "3/30/17",
    "store_license_operator": "刘普照",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "刘戈",
    "store_consume_complain_number": "58211228",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品2小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/57.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230111",
        "store_filing_project": "热食类食品制售,冷食类食品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "58",
    "store_brand": "麻辣E族",
    "store_name": "上海晶赢餐饮管理有限公司",
    "store_license_name": "上海晶赢餐饮管理有限公司第一分公司",
    "store_license_code": "91310115MA1H8Q7L55  ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-B1-1-012 ",
    "store_license_date": "3/16/17",
    "store_license_operator": "陆如茵",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "郑家强",
    "store_consume_complain_number": "50968377",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "食品2小时",
    "store_take_out_number": "50968377",
    "store_qrcode": "img/qrcodes/58.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245170",
        "store_filing_project": "热食类食品制售[仅限环保部门限定的不产生油烟的餐饮项目(麻辣烫店)]",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "59",
    "store_brand": "顺风",
    "store_name": "上海世佳顺风餐饮有限公司",
    "store_license_name": "上海世佳顺风餐饮有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8WDM8E ",
    "store_license_address": "上海市浦东新区川沙路5398号第五层G61-F05-1-001室 ",
    "store_license_date": "4/26/17",
    "store_license_operator": "吴稚亮",
    "store_license_scope": "餐饮服务，食品流通。",
    "store_facebook_level": "",
    "store_responsible_person": "郭宣城",
    "store_consume_complain_number": "18721684666",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品10小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/59.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150252005",
        "store_filing_project": "热食类食品制售,冷食类食品制售,生食类食品制售, 糕点类食品制售(中式干点 ),自制饮品制售",
        "store_filing_date": "5/31/22"
      }
    ]
  },
  {
    "id": "60",
    "store_brand": "老渝城",
    "store_name": "老渝城（上海）餐饮管理有限公司",
    "store_license_name": "老渝城（上海）餐饮管理有限公司川沙路分公司 ",
    "store_license_code": " 91310115MA1H8TBN5C  ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-008室 ",
    "store_license_date": "4/5/17",
    "store_license_operator": "李成",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "李成",
    "store_consume_complain_number": "15000883457",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品10小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/60.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150237897",
        "store_filing_project": "热食类食品制售,自制饮品制售,单纯经营火锅",
        "store_filing_date": "5/7/22"
      }
    ]
  },
  {
    "id": "61",
    "store_brand": "兰芳园",
    "store_name": "上海市浦东新区川沙新镇添好韵饮品店",
    "store_license_name": "上海市浦东新区川沙新镇添好韵饮品店",
    "store_license_code": "310115601795859",
    "store_license_address": "浦东新区川沙新镇川沙路5398号G61-F03-1-007B室 ",
    "store_license_date": "4/14/17",
    "store_license_operator": "凌月英",
    "store_license_scope": " 餐饮服务（现制现售饮料、冷冻饮品及果蔬）。",
    "store_facebook_level": "",
    "store_responsible_person": "刘小英",
    "store_consume_complain_number": "13701894627",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品24小时，食品10小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/61.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150231017",
        "store_filing_project": "糕点类食品制售(中式干点),自制饮品制售(风味饮料,茶,咖啡,植物饮料,冰淇淋,风味冰,水果甜品)[仅限环保部门限定的不产生油烟的餐饮项目]",
        "store_filing_date": "2/19/20"
      }
    ]
  },
  {
    "id": "62",
    "store_brand": "YOBA",
    "store_name": "上海滋虹食品有限公司",
    "store_license_name": "上海滋虹食品有限公司",
    "store_license_code": "91310115MA1H80R93C ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-007C室 ",
    "store_license_date": "7/20/16",
    "store_license_operator": "盛菲菲",
    "store_license_scope": "食品流通，食用农产品的销售，餐饮企业管理，餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "朱小姐",
    "store_consume_complain_number": "17717378402",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "酸奶冰淇淋半小时，酸奶7天",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/62.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150225169",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/13/22"
      }
    ]
  },
  {
    "id": "63",
    "store_brand": "望湘园",
    "store_name": "望湘园（上海）实业发展有限公司",
    "store_license_name": "望湘园（上海）实业发展有限公司川沙路店 ",
    "store_license_code": "91310115MA1H8W021B ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-007A室 ",
    "store_license_date": "4/24/17",
    "store_license_operator": "柳智",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "杨晓帆",
    "store_consume_complain_number": "13651712577",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品4小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/63.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150248670",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售",
        "store_filing_date": "5/25/22"
      }
    ]
  },
  {
    "id": "64",
    "store_brand": "大咀",
    "store_name": "碟膳餐饮管理（上海）有限公司",
    "store_license_name": "碟膳餐饮管理（上海）有限公司川沙路店 ",
    "store_license_code": "91310115MA1H8T0J2G ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F03-1-010室",
    "store_license_date": "3/31/17",
    "store_license_operator": "居丽",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "孙晓月",
    "store_consume_complain_number": "15906201170",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品4小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/64.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230179",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "65",
    "store_brand": "念吾村",
    "store_name": "上海宜会餐饮管理有限公司",
    "store_license_name": "上海宜会餐饮管理有限公司",
    "store_license_code": "91310115MA118W3W6N",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-005室",
    "store_license_date": "4/24/17",
    "store_license_operator": "陈明",
    "store_license_scope": "餐饮企业管理，餐饮服务，日用百货的销售",
    "store_facebook_level": "",
    "store_responsible_person": "师翠翠",
    "store_consume_complain_number": "18255889316",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/65.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150247123",
        "store_filing_project": "热食类食品制售，糕点类食品制售（中式干点）",
        "store_filing_date": "5/23/22"
      }
    ]
  },
  {
    "id": "66",
    "store_brand": "麻省理功",
    "store_name": "上海舌青餐饮有限公司",
    "store_license_name": "上海舌青餐饮有限公司",
    "store_license_code": "91310115MA1H8TY896 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-004室",
    "store_license_date": "4/12/17",
    "store_license_operator": "漆玉莲",
    "store_license_scope": "餐饮服务，餐饮企业管理。",
    "store_facebook_level": "",
    "store_responsible_person": "刘梦磊",
    "store_consume_complain_number": "15215234511",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2-3小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/66.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230469",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售",
        "store_filing_date": "4/24/22"
      }
    ]
  },
  {
    "id": "67",
    "store_brand": "西贝",
    "store_name": "上海西贝周昕餐饮管理有限公司",
    "store_license_name": "上海西贝周昕餐饮管理有限公司川沙分公司",
    "store_license_code": "91310115MA1H8UCX6K ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-001B室",
    "store_license_date": "4/17/17",
    "store_license_operator": "王金金",
    "store_license_scope": " 餐饮服务。 ",
    "store_facebook_level": "",
    "store_responsible_person": "张小明",
    "store_consume_complain_number": "18847709876",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/67.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232561",
        "store_filing_project": "热食类食品制售,冷食类食品制售",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "68",
    "store_brand": "小辉哥",
    "store_name": "上海龙辉餐饮管理有限公司",
    "store_license_name": "上海龙辉餐饮管理有限公司川沙百联店",
    "store_license_code": "91310115MA1H8UDC05",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-001A室 ",
    "store_license_date": "4/17/17",
    "store_license_operator": "洪瑞泽",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "刘本健",
    "store_consume_complain_number": "15670179505",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品24小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/68.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232553",
        "store_filing_project": "热食类食品制售,自制饮品制售,单纯经营火锅",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "69",
    "store_brand": "丁家里",
    "store_name": "上海丁家里餐饮连锁有限公司",
    "store_license_name": "上海丁家里餐饮连锁有限公司川沙店",
    "store_license_code": "91310115MA1H8U4648 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-010",
    "store_license_date": "4/13/17",
    "store_license_operator": "张雨双",
    "store_license_scope": "餐饮服务。 ",
    "store_facebook_level": "",
    "store_responsible_person": "王雅利",
    "store_consume_complain_number": "15000031077",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/69.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232579",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "70",
    "store_brand": "苍洱小镇",
    "store_name": "上海浦东苍洱餐饮有限公司",
    "store_license_name": "上海浦东苍洱餐饮有限公司",
    "store_license_code": "91310115MA1H8WL84C ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-003室",
    "store_license_date": "4/27/17",
    "store_license_operator": "王文渊",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "王小高",
    "store_consume_complain_number": "18856758467",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/70.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150250597",
        "store_filing_project": "热食类食品制售,冷食类食品制售",
        "store_filing_date": "5/26/22"
      }
    ]
  },
  {
    "id": "71",
    "store_brand": "新石器",
    "store_name": "上海领御餐饮管理有限公司",
    "store_license_name": "上海领御餐饮管理有限公司川沙路店",
    "store_license_code": "91310115MA1H8P1Y0N",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-009B室 ",
    "store_license_date": "3/6/17",
    "store_license_operator": "庄大庆",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "周淳",
    "store_consume_complain_number": "13761696159",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品6小时，食品冷藏18小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/71.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230187",
        "store_filing_project": "热食类食品制售,自制饮品制售,单纯经营烧烤",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "72",
    "store_brand": "左庭右院",
    "store_name": "上海左庭右院企业管理有限公司",
    "store_license_name": " 上海左庭右院企业管理有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8QF8XG ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-009A室",
    "store_license_date": "3/20/17",
    "store_license_operator": "郑坚",
    "store_license_scope": "餐饮服务。 ",
    "store_facebook_level": "",
    "store_responsible_person": "习媛",
    "store_consume_complain_number": "15618260400",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品6小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/72.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230195",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售,单纯经营火锅",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "73",
    "store_brand": "鱼到",
    "store_name": "上海诗宇餐饮管理有限公司",
    "store_license_name": "上海诗宇餐饮管理有限公司川沙分公司",
    "store_license_code": "91310115MA1H8RQR8B",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F02-1-009室",
    "store_license_date": "3/30/17",
    "store_license_operator": "蔡永春",
    "store_license_scope": "餐饮服务",
    "store_facebook_level": "",
    "store_responsible_person": "夏荣荣",
    "store_consume_complain_number": "18717856509",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品4小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/73.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150245365",
        "store_filing_project": "热食类食品制售，冷食类食品制售，自制饮品制售",
        "store_filing_date": "5/21/22"
      }
    ]
  },
  {
    "id": "74",
    "store_brand": "翠蝶",
    "store_name": "上海翠味餐饮有限公司",
    "store_license_name": "上海翠味餐饮有限公司 ",
    "store_license_code": "91310115MA1H8UJM0T",
    "store_license_address": "上海市浦东新区川沙路5398号二层G61-F02-1-008室 <br/> ",
    "store_license_date": "4/19/17",
    "store_license_operator": "孙田华",
    "store_license_scope": "餐饮企业管理，餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "徐思琪",
    "store_consume_complain_number": "15692173873",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/74.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230427",
        "store_filing_project": "热食类食品制售,冷食类食品制售, 糕点类食品制售(不含冷加工糕点 ),自制饮品制售",
        "store_filing_date": "4/24/22"
      }
    ]
  },
  {
    "id": "75",
    "store_brand": "乐凯撒",
    "store_name": "上海无乐不作餐饮管理有限公司",
    "store_license_name": "上海无乐不作餐饮管理有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8QJ34Y ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-013A室",
    "store_license_date": "3/20/17",
    "store_license_operator": "张霆",
    "store_license_scope": "餐饮企业管理，餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "王小平",
    "store_consume_complain_number": "13817673805",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/75.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230080",
        "store_filing_project": "热食类食品制售,冷食类食品制售,自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "76",
    "store_brand": "哈根达斯",
    "store_name": "通用磨坊贸易(上海)有限公司",
    "store_license_name": " 通用磨坊贸易（上海）有限公司川沙百联店 ",
    "store_license_code": "91310000778522950E ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-014室",
    "store_license_date": "10/9/02",
    "store_license_operator": "郑珏",
    "store_license_scope": "供应Haagen－Dazs品牌的冰淇淋、糕点、巧克力食品和广告礼品，以及堂饮的饮料和酒（涉及行政许可的，凭许可证经营）。 ",
    "store_facebook_level": "",
    "store_responsible_person": "梁俊杰",
    "store_consume_complain_number": "13916375383",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "冰淇淋开罐后14日安",
    "store_take_out_number": "4009870870",
    "store_qrcode": "img/qrcodes/76.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230217",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "77",
    "store_brand": "雪茄先生",
    "store_name": "上海雅隆贸易有限公司",
    "store_license_name": "上海雅隆贸易有限公司 ",
    "store_license_code": "91310115680970448E ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-010D室 <br/> ",
    "store_license_date": "9/25/08",
    "store_license_operator": "陈济",
    "store_license_scope": "日用化工产品的研制开发，化工产品（除危险化学品、监控化学品、烟花爆竹、民用爆炸物品、易制毒化学品）、包装材料、日用百货、文化用品、五金交电、卫生洁具、装潢材料、建筑材料、钢材、木制品的销售，烟草专卖零售，房地产经纪，园林绿化，景观设计，会务服务，从事货物及技术的进出口业务，投资咨询，食品流通 。",
    "store_facebook_level": "",
    "store_responsible_person": "陈济",
    "store_consume_complain_number": "13482534858",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/77.png",
    "store_filings": [
      {
        "store_filing_code": "JY13101150225737",
        "store_filing_project": "预包装食品销售( 含冷藏冷冻食品 )",
        "store_filing_date": "4/16/22"
      }
    ]
  },
  {
    "id": "78",
    "store_brand": "避风塘",
    "store_name": "上海避风塘美食有限公司",
    "store_license_name": "上海避风塘美食有限公司川沙路店 ",
    "store_license_code": "91310115MA1H8R5B3H",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-008室",
    "store_license_date": "3/24/17",
    "store_license_operator": "程蔚",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "张文",
    "store_consume_complain_number": "13601850654",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/78.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150230099",
        "store_filing_project": "热食类食品制售,冷食类食品制售, 糕点类食品制售(不含冷加工糕点 ),自制饮品制售",
        "store_filing_date": "4/23/22"
      }
    ]
  },
  {
    "id": "79",
    "store_brand": "海客",
    "store_name": "上海品然餐饮管理有限公司",
    "store_license_name": " 上海品然餐饮管理有限公司川沙分公司 ",
    "store_license_code": "91310115MA1H8U5F47 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F04-1-002",
    "store_license_date": "4/13/17",
    "store_license_operator": "何迎飞",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "岳雷",
    "store_consume_complain_number": "18222270727",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品6小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/79.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150232545",
        "store_filing_project": "热食类食品制售,冷食类食品制售",
        "store_filing_date": "4/27/22"
      }
    ]
  },
  {
    "id": "80",
    "store_brand": "红宝石",
    "store_name": "红宝石食品有限公司",
    "store_license_name": "红宝石食品有限公司川沙路店",
    "store_license_code": "91310000MA1FY6LH78 ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-013B室",
    "store_license_date": "4/25/17",
    "store_license_operator": "应酉定",
    "store_license_scope": "餐饮服务，食品流通（仅限销售总公司生产的糕点，粮食除外）。",
    "store_facebook_level": "",
    "store_responsible_person": "石慕荣",
    "store_consume_complain_number": "15021896103",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品2小时，食品48小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/80.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150234741",
        "store_filing_project": "自制饮品制售",
        "store_filing_date": "5/2/22"
      }
    ]
  },
  {
    "id": "81",
    "store_brand": "星巴克",
    "store_name": "上海统一星巴克咖啡有限公司",
    "store_license_name": "上海市浦东新区川沙路5398号G61-F01-1-012室 ",
    "store_license_code": "91310000MA1FP70M8Y",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-012室 ",
    "store_license_date": "5/17/17",
    "store_license_operator": "董寅鸣",
    "store_license_scope": "餐饮服务,零售咖啡用具、带有星巴克标志的纪念品及其他与咖啡店运营相关的商品和工艺品。",
    "store_facebook_level": "",
    "store_responsible_person": "王雁",
    "store_consume_complain_number": "13917954391",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品1小时，食品12小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/81.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150251973",
        "store_filing_project": "自制饮品制售,预包装食品销售( 含冷藏冷冻食品 )",
        "store_filing_date": "5/31/22"
      }
    ]
  },
  {
    "id": "82",
    "store_brand": "巴黎贝甜",
    "store_name": "上海笑乐商贸发展有限公司",
    "store_license_name": "上海笑乐商贸发展有限公司川沙分公司",
    "store_license_code": "91310115MA1H8LR90K ",
    "store_license_address": "上海市浦东新区川沙路5398号G61-F01-1-015室 <br/> ",
    "store_license_date": "2/7/17",
    "store_license_operator": "CHOI KEW YOUL（崔圭烈）",
    "store_license_scope": "餐饮服务。",
    "store_facebook_level": "",
    "store_responsible_person": "吴文涛",
    "store_consume_complain_number": "18001723139",
    "store_market_level": "",
    "store_admin_punish_records": "暂无",
    "store_consume_dispute_records": "暂无",
    "store_product_care": "",
    "store_product_instructions": "饮品3小时，食品24小时",
    "store_take_out_number": "",
    "store_qrcode": "img/qrcodes/82.png",
    "store_filings": [
      {
        "store_filing_code": "JY23101150227539",
        "store_filing_project": "糕点类食品制售(含冷加工糕点),自制饮品制售,预包装食品销售(含冷藏冷冻食品),散装食品销售(含冷藏冷冻食品,不含熟食)",
        "store_filing_date": "4/18/22"
      }
    ]
  }
]

